apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{.Values.ws_api.image.repository}}:{{.Values.ws_api.image.tag | default .Chart.AppVersion}}"
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://db:5432/postgres"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "ZXhhbXBsZQ=="
          # - name: DB_HOST
          #   value: ws-db-service
          # - name: DB_PORT
          #   value: "5432"
          # - name: DB_NAME
          #   valueFrom:
          #     configMapKeyRef:
          #       name: ws-db-configmap
          #       key: database-name
          # - name: DB_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: ws-db-secret
          #       key: username
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: ws-db-secret
          #       key: password
      # imagePullSecrets:
      # - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
