apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-api
  template:
    metadata:
      labels:
        app: ws-api
    spec:
      containers:
        - name: ws-api
          image: "{{.Values.ws_api.image.repository}}:{{.Values.ws_api.image.tag | default .Chart.AppVersion}}"
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ws-api-service
spec:
  selector:
    app: ws-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080