apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{.Values.ws_db.image.repository}}:{{.Values.ws_db.image.tag | default .Chart.AppVersion}}"
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "example"
            - name: POSTGRES_DB
              value: "postgres"
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: ws-secrets
            #       key: POSTGRES_USER
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: ws-secrets
            #       key: POSTGRES_PASSWORD
            # - name: POSTGRES_DB
            #   valueFrom:
            #     secretKeyRef:
            #       name: ws-secrets
            #       key: POSTGRES_DB

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432