apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.ws_web.image.repository }}:{{ .Values.ws_web.image.tag | default .Chart.AppVersion }}"
          ports:
          - containerPort: 80
          env:
          # - name: API_HOST
          #   value: ws-api-service  # Name of the API service
          # - name: API_PORT
          #   value: "8080"
          - name: API_URL
            value: http://backend:8080
      # imagePullSecrets:
      # - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
